networks:
  impelIt-net:
    external: true
volumes:
  impelIt-redis:
    name: 'impelIt-redis'
  impelIt-mysql:
    name: 'impelIt-mysql'

services:

  web:
    restart: "no"
    volumes:
      - ../codes/public:/var/www/html/public
    ports:
      - ${HTTP_PUBLISH_PORT}:80
    networks:
      impelIt-net:
        aliases:
          - impelIt-web

  app:
    env_file:
      - .envs/app.env
      - .envs/php-ini.env
    restart: "no"
    volumes:
      - ../codes:/var/www/html
    networks:
      impelIt-net:
        aliases:
          - impelIt-app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    container_name: redis-server
    env_file:
      - .envs/redis.env
    ports:
      - ${REDIS_PUBLISH_PORT}:6379
    networks:
      impelIt-net:
        aliases:
          - impelIt-redis
    volumes:
      - impelIt-redis:/data

  mysql:
    env_file:
      - .envs/mysql.env
    ports:
      - ${MYSQL_PUBLISH_PORT}:3306
    volumes:
      - impelIt-mysql:/var/lib/mysql
      - ./mysql/sqls:/sqls
    networks:
      impelIt-net:
        aliases:
          - impelIt-mysql

#  scheduler:
#    env_file:
#      - .envs/app.env
#      - .envs/php-ini.env
#    volumes:
#      - ../codes:/var/www/html
#    networks:
#      impelIt-net:
#        aliases:
#          - impelIt-scheduler